version: "3"


services:
  mysql-master:
    image: mysql:5.6
    container_name: mysql-master
    volumes:
      - ./pkg/mysql/data:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      - --default-authentication-plugin=mysql_native_password
