version: "3"


services:
  mysql-master:
    image: mysql:5.6
    restart: on-failure
    container_name: mysql-master
    volumes:
      - ./pkg/mysql/data:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      - --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
    container_name: seckill-redis
    volumes:
      - ./pkg/redis/conf/redis.conf:/etc/redis/redis.conf
      - /pkg/redis/data:/data
    ports:
      - "9920:6379"
    privileged: true
  nginx:
    image: nginx:1.21
    restart: always
    container_name: seckill-nginx
    volumes:
      - ./pkg/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./pkg/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    privileged: true
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: seckill-etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - "9930:2379"
  zookeeper:
    image: zookeeper:latest
    restart: always
    container_name: seckill-zookeeper
    volumes:
      - ./pkg/zookeeper/conf:/conf
      - ./pkg/zookeeper/data:/data
      - ./pkg/zookeeper/logs:/datalog
    ports:
      - "9940:2181"