// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"seckill/cmd/api/biz/router"
)

func main() {
	h := server.Default()
	router.GeneratedRegister(h)
	h.Spin()
}
