// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app/server"
	"seckill/cmd/api/biz/router"
	"seckill/cmd/task"
)

func main() {
	h := server.Default()

	router.GeneratedRegister(h)
	task.StartAllTask(context.Background())
	h.Spin()
}
