// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderStatus = "orderStatus"

// OrderStatus mapped from table <orderStatus>
type OrderStatus struct {
	ID     int64   `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:è®¢å•å·" json:"id"`                                // è®¢å•å·
	UID    int64  `gorm:"column:uid;type:bigint(20) unsigned;comment:ç”¨æˆ·å·" json:"uid"`                                         // ç”¨æˆ·å·
	Pid    int32  `gorm:"column:pid;type:int(10) unsigned;comment:å•†å“å·" json:"pid"`                                            // å•†å“å·
	Status string `gorm:"column:status;type:enum('Created','Doing','Finished');default:Created;comment:è®¢å•çŠ¶æ€" json:"status"` // è®¢å•çŠ¶æ€
}

// TableName OrderStatus's table name
func (*OrderStatus) TableName() string {
	return TableNameOrderStatus
}
