// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserInfo1 = "userInfo_1"

// UserInfo1 mapped from table <userInfo_1>
type UserInfo1 struct {
	ID        int32                 `gorm:"column:id;type:int(10) unsigned;primaryKey;comment:ä¸»é”®" json:"id"`      // ä¸»é”®
	Email     string                `gorm:"column:email;type:varchar(20);not null;comment:é‚®ç®±" json:"email"`       // é‚®ç®±
	Password  string                `gorm:"column:password;type:varchar(30);not null;comment:å¯†ç " json:"password"` // å¯†ç 
}

// TableName UserInfo1's table name
func (*UserInfo1) TableName() string {
	return TableNameUserInfo1
}
