// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
	
)

const TableNameUserOrder1 = "user_order_1"

// UserOrder mapped from table <user_order_1>
type UserOrder struct {
	ID        int64                 `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:è®¢å•id" json:"id"` // è®¢å•id
	UID       int64                `gorm:"column:uid;type:bigint(20) unsigned;comment:ç”¨æˆ·id" json:"uid"`          // ç”¨æˆ·id
	Pid       int32                `gorm:"column:pid;type:int(10) unsigned;comment:å•†å“id" json:"pid"`             // å•†å“id
	CreatedAt *time.Time            `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
}

// TableName UserOrder1's table name
func (*UserOrder) TableName() string {
	return TableNameUserOrder1
}
