// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productaddMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _doseckillMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitMw() []app.HandlerFunc {
	// your code...
	return nil
}
