// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"seckill/cmd/api/biz/router/api"
	"seckill/conf"
)

func main() {
	conf.LoadConf()
	h := server.Default()

	api.Register(h)
	h.Spin()
}
